version: '3'

services:
  gateway:
    image: 707713018591.dkr.ecr.eu-west-1.amazonaws.com/main-gateway:1.0    
    ports:
      - "5000:5000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: nestjs-tcp-microservices
        awslogs-region: eu-west-1
        awslogs-stream-prefix: main-gateway
  service-a:
    image: 707713018591.dkr.ecr.eu-west-1.amazonaws.com/service-a:1.0
  service-b:
    image: 707713018591.dkr.ecr.eu-west-1.amazonaws.com/service-b:1.0