version: '3'

services:
  gateway:
    build: 
      context: gateways/main-gateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend
  service-a:
    build: 
      context: services/service-a/
      dockerfile: Dockerfile
    restart: always    
    networks:
      - backend
  service-b:
    build:
      context: services/service-b/
      dockerfile: Dockerfile
    restart: always    
    networks:
      - backend
networks:
  backend:
    driver: bridge