version: '3'

services:
  gateway:
    build: ./gateways/main-gateway
    restart: always
    ports:
      - "5000:5000"
    networks:
      - backend
  service-a:
    build: ./services/service-a
    restart: always    
    networks:
      - backend
  service-b:
    build: ./services/service-b
    restart: always    
    networks:
      - backend
networks:
  backend:
    driver: bridge