version: '3'

services:
  gateway:
    build: 
      context: gateways/main-gateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:8080"
    networks:
      - backend
  service-a:
    hostname: service-a
    build: 
      context: services/service-a/
      dockerfile: Dockerfile
    restart: always    
    networks:
      - backend
  service-b:
    hostname: service-b
    build:
      context: services/service-b/
      dockerfile: Dockerfile
    restart: always    
    networks:
      - backend
networks:
  backend:
    driver: bridge